### ISSUE TITLE
Upgrade to the latest guard/listen and convert to Celluloid

### ISSUE THREAD

**Issue by acant** [nesquena/gitdocs#101]
I have been looking at replacing EventMachine with Celluloid. Then we could upgrade to the latest guard and listen gems, which are based on Celluloid.
I think it could improve performance, and also give access to some newer notification options implemented in Guard.

Unless there are any objections, I will start working on the conversion.

**Comment by nesquena** [comment]
I think that could make sense, thanks for suggesting it.

**Comment by acant** [comment]
Finally got the conversion working in #117, #119 and #120. Closing the issue as completed.

**Comment by nesquena** [comment]
:thumbsup:
