### ISSUE TITLE
Link in repo description is dead

### ISSUE THREAD

**Issue by hellyeah** [nesquena/gitdocs#103]
The link (http://engineering.gomiso.com/2011/11/30/collaborate-and-track-tasks-with-ease-using-gitdocs/) in the repo description points to this: ![screen shot 2015-07-01 at 9 22 53 pm](https://cloud.githubusercontent.com/assets/1475361/8469919/857ed858-2037-11e5-838b-3ecc617f3af7.png)

**Comment by nesquena** [comment]
Fixed to https://blog.codepath.com/2011/11/30/collaborate-and-track-tasks-with-ease-using-gitdocs/
