### ISSUE TITLE
Releasing v0.6.0

### ISSUE THREAD

**Issue by acant** [nesquena/gitdocs#122]
@nesquena Now that the celluloid conversion is finished, I would like to get v0.6.0 released.

I have some new feature ideas that could go into a new version.
Additionally, the latest version of the listen gem will require dropping support for Ruby 1.9, which seems like something that should come after a new version.

We could do one more pre, but I have been using the latest code on my own machine and it seems to be working fine. Any objections to a new version?

**Comment by nesquena** [comment]
Yep, great idea! Pushed https://rubygems.org/gems/gitdocs. Thanks again for keeping this project going! Makes sense to drop ruby 1.9 in our next major release.

**Comment by acant** [comment]
Huzzah! And closing this because 0.6.0 is out. and then so was 0.6.1 to make sure that everything exist properly. :)
@nesquena thanks for continuing to merge and release the code that I have sent
