### ISSUE TITLE
Trouble installing, starting gitdocs

### ISSUE THREAD

**Issue by quite** [nesquena/gitdocs#99]
I've had to reinstall the system where I was previously successfully running gitdocs (pre3, 4 or so).

First try is to do: gem install gitdocs --pre
This results in a gitdocs executable which, when I do: gitdocs start, I get:
"Daemonized process couldn't be started, Failed to start gitdocs". And I don't know how to get further debug information. No --debug?

Another attempt is cloning this very repository, and trying to "rake", but then I run into a lot of problems like "... Unable to activate coveralls-0.7.2, because thor-0.14.6 conflicts with thor (= 0.18.1)". And so on. One might think that the above try would have installed all neccessary gems of the right version, but perhaps that is the actual problem above as well!

I would be happy to start running gitdocs again! : )

**Comment by nesquena** [comment]
As outlined here: https://github.com/nesquena/gitdocs#starting-gitdocs start gitdocs in debug mode and let us know what the logs say.

**Comment by acant** [comment]
> This results in a gitdocs executable which, when I do: gitdocs start, I get:
"Daemonized process couldn't be started, Failed to start gitdocs". And I don't know how to get further debug information. No --debug?

@quite the failure to daemonize message can mean that another copy of gitdocs is already running. You can check this by running:
```
gitdocs stop
ps ax | grep gitdocs
```
If the output is empty, then you should be able to start
If it is not empty then kill the stray gitdocs processes first, and then try to re-start.

If this still does not work then you can try starting in debug mode with:
```
gitdocs start -D
```
(as described in the docs that @nesquena mentioned) and let us know what messages are displayed.


> Another attempt is cloning this very repository, and trying to "rake", but then I run into a lot of problems 

You do need to use [bundler](http://bundler.io/) to run things in the repository, but this is not documented. I really should add a section about this. So if you want to clone and then see the possible rake tasks you would do the following:
```
gem install bundler
git clone git@github.com:nesquena/gitdocs.git
cd gitdocs
bundler install # which should install all the dependencies
bundle exec rake -T # which should show the available rake tasks
```

At this point you would be able to run the from the repository with:
```
bundler exec gitdocs start
```
(again being careful that you are not already running another copy of gitdocs already)

Sorry for the late reply, but I hope that this information is help.
 And I look forward to hearing about any progress you make.

**Comment by quite** [comment]
Sorry, I've not had the time to try and set up gitdocs again after running
into this problem. Probably what you both write will help me solve this,
once I do get the time (apparantly my need for gitdocs isn't very big
currently :) So I think it's safe to close this.

**Comment by acant** [comment]
Cool. I will close it for now. But I'll follow up on the bundler docs and see about adding more details to the failure to start message.
